{"name": "test_login_negative_shows_error[standard_user-wrong_password]", "status": "passed", "steps": [{"name": "Логин", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1757407324679, "stop": 1757407325724}], "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1757407324354, "stop": 1757407325787, "uuid": "1b45eff8-eabb-4a81-8f31-c1783b0ec93e", "historyId": "7b688b1f7c5a94585c7d19a613424f16", "testCaseId": "4075f5f56554ec24a79f4d66f84a44d9", "fullName": "tests.test_auth#test_login_negative_shows_error", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "Zak"}, {"name": "thread", "value": "12240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}], "titlePath": ["tests", "test_auth.py"]}