{"name": "test_login_negative_shows_error[standard_user-wrong_password]", "status": "passed", "steps": [{"name": "Логин", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1757407193155, "stop": 1757407193736}], "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1757407193058, "stop": 1757407193874, "uuid": "3d1f2d5e-459a-4b20-973a-071ac6faa647", "historyId": "7b688b1f7c5a94585c7d19a613424f16", "testCaseId": "4075f5f56554ec24a79f4d66f84a44d9", "fullName": "tests.test_auth#test_login_negative_shows_error", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "Zak"}, {"name": "thread", "value": "12376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}], "titlePath": ["tests", "test_auth.py"]}