{"name": "test_login_negative_shows_error[standard_user-]", "status": "passed", "steps": [{"name": "Логин", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "''"}], "start": 1757407326875, "stop": 1757407327111}], "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "''"}], "start": 1757407326483, "stop": 1757407327143, "uuid": "6240151f-57d3-42ef-ab6b-dfbc16de547b", "historyId": "b099ffad2fe812c92aeff674440c9674", "testCaseId": "4075f5f56554ec24a79f4d66f84a44d9", "fullName": "tests.test_auth#test_login_negative_shows_error", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "Zak"}, {"name": "thread", "value": "12240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}], "titlePath": ["tests", "test_auth.py"]}