{"name": "test_login_negative_shows_error[-secret_sauce]", "status": "passed", "steps": [{"name": "Логин", "status": "passed", "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1757407326216, "stop": 1757407326442}], "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1757407325819, "stop": 1757407326476, "uuid": "6e1f58d4-3024-4f0d-b94c-3133429a900b", "historyId": "0ddf58633960c03c1c4ad304ebfec89d", "testCaseId": "4075f5f56554ec24a79f4d66f84a44d9", "fullName": "tests.test_auth#test_login_negative_shows_error", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "Zak"}, {"name": "thread", "value": "12240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}], "titlePath": ["tests", "test_auth.py"]}